In [26]:
import numpy as np
from scipy.spatial.transform import Rotation
angle=np.array([3.102297711705674, 0.023205965984677442, 0.8183563132048056])
r = Rotation.from_euler('xyz', angle)
quaternion = r.as_quat()
print(quaternion)

r = Rotation.from_quat(quaternion)
euler_angles = r.as_euler('xyz')
print(euler_angles)



[ 0.9171186   0.39796103 -0.00282702  0.02263848]
[3.10229771 0.02320597 0.81835631]


In [2]:
import pybullet as p
p.connect(p.GUI)
p.resetSimulation()
p.setGravity(0,0,-9.8)
p.setTimeStep(1./60)
p.setRealTimeSimulation(0)

id = p.loadURDF("data/urdfs/panda/robotiq_85.urdf")
numJoints = p.getNumJoints(id)
joints_indexes = [i for i in range(numJoints) if p.getJointInfo(id, i)[2] != p.JOINT_FIXED]  # 可以使用的关节索引
print([p.getJointInfo(id, i) for i in joints_indexes])


error: Only one local in-process GUI/GUI_SERVER connection allowed. Use DIRECT connection mode or start a separate GUI physics server (ExampleBrowser, App_SharedMemoryPhysics_GUI, App_SharedMemoryPhysics_VR) and connect over SHARED_MEMORY, UDP or TCP instead.

: 

In [3]:
import rospy
import RobotControl_func_ros1 as RobotControl_func
import cv_bridge

cv_bridge = cv_bridge.CvBridge()

# #可能從這裡取得的 task到cam
# cam_frame_id = rospy.get_param("~cam/frame_id")
# img = cv_bridge.imgmsg_to_cv2(msg).astype(np.float32) * 0.001
# T_cam_task = tf_tree.lookup(
#     cam_frame_id, "task", msg.header.stamp, rospy.Duration(0.1)
# )

In [7]:

import pyrealsense2 as rs
pipeline = rs.pipeline()
config = rs.config()
config.enable_stream(rs.stream.depth, 640, 480, rs.format.z16, 30)
config.enable_stream(rs.stream.color, 640, 480, rs.format.rgb8, 30)
cfg = pipeline.start(config)
profile = cfg.get_stream(rs.stream.depth)
intr = profile.as_video_stream_profile().get_intrinsics()
print(intr)  #

[ 640x480  p[320.475 233.976]  f[382.94 382.94]  Brown Conrady [0 0 0 0 0] ]


[[ 0.99959658 -0.00447668 -0.02804718]
 [ 0.00441263  0.99998751 -0.00234523]
 [ 0.02805733  0.00222052  0.99960385]]
[[-85.23109251]
 [-73.48531014]
 [355.95850582]]  目前位置的相機外參

In [17]:
import rospy
import RobotControl_func_ros1 as RobotControl_func

rospy.init_node("RobotControl",anonymous=True)
robot = RobotControl_func.RobotControl_Func()
totallist=[]
[x,y,z,u,v,w] = robot.get_TMPos()
print([x,y,z,u,v,w])

$$$$$$$
(0.2126485137939453, -0.5746722412109375, 0.11454066467285157, -3.0813151981091575, 0.02319790784178535, 0.8021553056084448)
$$$$$$$
[212.6485137939453, -574.6722412109375, 114.54066467285156, -3.0813151981091575, 0.02319790784178535, 0.8021553056084448]


每次取得一個點位並寫入

In [91]:
robot.get_TMPos()
print(robot.get_TMPos())
totallist.append(robot.get_TMPos())
print(type(robot.get_TMPos()))


(-0.02632029724121094, -0.356956787109375, 0.411585693359375, 2.831134383197697, -0.5038458767665858, -0.16469119674628832)
(-5.605193857299268e-48, -5.605193857299268e-48, 5.605193857299268e-48, 9.782908802243343e-47, -9.782908802243343e-47, 9.782908802243343e-47)
(-0.02632029724121094, -0.356956787109375, 0.411585693359375, 2.831134383197697, -0.5038458767665858, -0.16469119674628832)
(-5.605193857299268e-48, -5.605193857299268e-48, 5.605193857299268e-48, 9.782908802243343e-47, -9.782908802243343e-47, 9.782908802243343e-47)
[233.795304093496, -271.0178254177077, 411.585693359375, 162.21205139160156, -28.868242263793945, -9.436110496520996]
(-0.02632029724121094, -0.356956787109375, 0.411585693359375, 2.831134383197697, -0.5038458767665858, -0.16469119674628832)
(-5.605193857299268e-48, -5.605193857299268e-48, 5.605193857299268e-48, 9.782908802243343e-47, -9.782908802243343e-47, 9.782908802243343e-47)
(-0.02632029724121094, -0.356956787109375, 0.411585693359375, 2.831134383197697, -0.

In [95]:
print(len(totallist))
print(totallist) #顯示目前儲存的

20
[[594.0838069345818, -138.5408801148759, 467.4356994628906, -173.66317749023438, 1.6348413228988647, 40.24143981933594], [651.1750404833966, -137.92859227889605, 377.5372314453125, -161.86044311523438, 6.094341278076173, 43.08310317993164], [380.57412494766294, -154.7507657518352, 465.6792907714844, 155.37606811523438, 0.7027701139450073, 40.455318450927734], [552.544283046787, 91.85597185453206, 469.34497070312506, -178.34031677246094, 26.35577392578125, 79.72480773925783], [505.931211898094, 40.430569496767646, 417.74749755859375, -178.93786621093753, 24.97023963928223, 77.29475402832031], [379.65062208488035, -171.83297921094038, 396.77734375, 149.84552001953128, -2.5344710350036626, 37.02196502685547], [313.1101271400841, -216.13275617872853, 464.00189208984375, 165.38563537597656, -8.392745971679688, 7.755660057067872], [316.2141420548246, -218.0021395206294, 411.0020446777344, 164.49418640136716, -22.723831176757812, 1.4787429571151733], [233.0353363977323, -175.30989595431373

把點位寫入

In [94]:
file_name = 'EIH_PosSet.txt'
with open(file_name, 'w+') as file:
    for sublist in totallist:
        file.write(str(sublist))
        file.write('\n')

In [5]:
import numpy as np

print([3.1219031047025103 * 180 / np.pi, 0.021591066711545426* 180 / np.pi, 0.8871005570020483* 180 / np.pi])

[178.87187194824222, 1.2370769977569582, 50.827117919921875]


In [10]:
[x,y,z,u,v,w] = robot.get_TMPos()
print([x,y,z,u,v,w])


#robot.set_TMPos([x,y,z-100,u,v,w])

$$$$$$$
(0.20950041198730468, -0.3604853515625, 0.10233863830566406, -3.1144800757961324, 0.03408715117841522, 0.922632851740049)
$$$$$$$
[209.5004119873047, -360.4853515625, 102.33863830566406, -3.1144800757961324, 0.03408715117841522, 0.922632851740049]


In [145]:
robot.set_TMPos(
[315.3041076660156, -457.3834228515625, 305.3858642578125, 3.0696172630209846, 2.445537041037089e-06, 0.7746355970631383]
)       
#回正中間高度一定要大於100才不會撞到

[0.3221174926757813, -0.5180438842773437, 0.46743569946289065, -3.0309942366798928, 0.028533363832244956, 0.7023456205905642]
[INFO] [1706959269.428046]: point 1 (Tag 1) is reached


In [108]:
[x,y,z,u,v,w]=[100, 100, 100.4959716796875, -176.01728820800784, 0.5390524864196777, 46.80111312866211]
robot.set_TMPos([564.4543755213471, -172.14735558855622, 398.3766174316407, -167.48153686523438, -10.199124336242678, 27.746347427368164])#mm  | x+    <- y+   z+是往上
#一定要大於100才不會撞到
#robot.set_TMPos([484.1042532418399, -86.53510553787287, 396.6761474609375, -178.4583587646484, -0.2089095413684845, 44.86580276489258])
#z軸似乎比實際上少了3公分

[0.2774029541015625, -0.5208560791015625, 0.39837661743164066, -2.9231042545986026, -0.17800830048771593, 0.4842651180098327]
[INFO] [1706957149.165105]: point 1 (Tag 1) is reached


In [1]:
from gripper import Gripper

In [7]:
from gripper import Gripper
G = Gripper()
G.gripper_soft_off()


Response: b'091003e800030130'
Close gripper
Response: b'091003e800030130'


In [5]:
G.gripper_reset()

Activate gripper:
Clear: 09 10 03 E8 00 03 06 00 00 00 00 00 00 73 30
Response: b'091003e800030130'
Set: 09 10 03 E8 00 03 06 01 00 00 00 00 00 72 E1
b'D z@\xa0 \xcc'
b'\t\x03\x021\x00L\x15'
Activate Complete


In [10]:
G.gripper_on()

Open gripper
Response: b'091003e800030130'


In [11]:
G.gripper_soft_off()
#G.gripper_on()

Close gripper
Response: b'091003e800030130'


In [35]:
G.gripper_status()

NameError: name 'G' is not defined

In [1]:
import numpy as np

print(np.load('Camera2Gripper.npy')) #偏移矩陣

print(np.load('RC2G.npy')) #旋轉矩陣

print(np.load('INS.npy')) #內參矩陣


[[-9.99523694e-01  2.23258360e-02  2.13059047e-02  3.12689041e+01]
 [-2.32043880e-02 -9.98851480e-01 -4.19198950e-02 -8.59567950e+01]
 [ 2.03455377e-02 -4.23943188e-02  9.98893779e-01 -1.14847755e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 0.99888145 -0.04660927  0.00796429]
 [ 0.04537618  0.99223829  0.11577645]
 [-0.01329873 -0.11528555  0.99324337]]
[[606.77737126   0.         321.63287183]
 [  0.         606.70030146 236.95293136]
 [  0.           0.           1.        ]]


In [20]:
import cv2
def RotationTrans(v): #轉旋轉矩陣
    #目前是使用弧度
    # print("----------VVVVVV------")
    # print("v:",v)
    #pi = np.pi / 180 #轉成弧度
    # tmp_v = v[0]
    # v[0] = v[2]
    # v[2] = tmp_v
    # pi =   1
    r1_mat = np.zeros((3, 3), np.float32)
    r2_mat = np.zeros((3, 3), np.float32)
    r3_mat = np.zeros((3, 3), np.float32)

    r = np.zeros((3, 1), np.float32)
    r[0] = 0
    r[1] = 0
    #r[2] = float(v[2]) * pi # 如果是角度轉成弧度
    r[2] = float(v[2]) 
    r3_mat, jacobian = cv2.Rodrigues(r)
    # print("r3_mat:",r3_mat)
    r[0] = 0
    r[1] = float(v[1])
    r[2] = 0
    # print('ys ', math.sin(v[1]))
    # print('yc ', math.cos(v[1]))
    r2_mat, jacobian = cv2.Rodrigues(r)
    # print("r2_mat:",r2_mat)
    r[0] = float(v[0])
    r[1] = 0
    r[2] = 0
    r1_mat, jacobian = cv2.Rodrigues(r)
    # print("r1_mat:",r1_mat)

    result = np.dot(np.dot(r3_mat, r2_mat), r1_mat)
    # print(v)
    # v = [element / 180 * np.pi for element in v]
    # print(v)
    # rxs = math.sin(v[0])
    # rxc = math.cos(v[0])
    # rys = math.sin(v[1])
    # ryc = math.cos(v[1])
    # rzs = math.sin(v[2])
    # rzc = math.cos(v[2])

    # r1_mat = np.array([[1,0,0],[0, rxc, -rxs], [0, rxs, rxc]])
    # print(r1_mat)
    # r2_mat = np.array([[ryc,0,rys],[0, 1, 0], [-rys, 0, ryc]])
    # print(r2_mat)
    # r3_mat = np.array([[rzc,-rzs,0],[rzs, rzc, 0], [0, 0, 1]])
    # print(r3_mat)
    
    

    # result = np.dot(np.dot(r3_mat, r2_mat), r1_mat)
    
    # print('result')
    print(result)
    return result

RotationTrans([-3.0813151981091575, 0.02319790784178535, 0.8021553056084448]) #放弧度

[[ 0.6949719   0.7165791  -0.05940002]
 [ 0.7186626  -0.69490093  0.02523281]
 [-0.02319583 -0.06022467 -0.99791527]]


array([[ 0.6949719 ,  0.7165791 , -0.05940002],
       [ 0.7186626 , -0.69490093,  0.02523281],
       [-0.02319583, -0.06022467, -0.99791527]], dtype=float32)

In [21]:
import numpy as np

def rotation_matrix_to_quaternion(R):
    trace = np.trace(R)
    if trace > 0:
        S = 0.5 / np.sqrt(trace + 1.0)
        w = 0.25 / S
        x = (R[2, 1] - R[1, 2]) * S
        y = (R[0, 2] - R[2, 0]) * S
        z = (R[1, 0] - R[0, 1]) * S
    elif R[0, 0] > R[1, 1] and R[0, 0] > R[2, 2]:
        S = 2.0 * np.sqrt(1.0 + R[0, 0] - R[1, 1] - R[2, 2])
        w = (R[2, 1] - R[1, 2]) / S
        x = 0.25 * S
        y = (R[0, 1] + R[1, 0]) / S
        z = (R[0, 2] + R[2, 0]) / S
    elif R[1, 1] > R[2, 2]:
        S = 2.0 * np.sqrt(1.0 + R[1, 1] - R[0, 0] - R[2, 2])
        w = (R[0, 2] - R[2, 0]) / S
        x = (R[0, 1] + R[1, 0]) / S
        y = 0.25 * S
        z = (R[1, 2] + R[2, 1]) / S
    else:
        S = 2.0 * np.sqrt(1.0 + R[2, 2] - R[0, 0] - R[1, 1])
        w = (R[1, 0] - R[0, 1]) / S
        x = (R[0, 2] + R[2, 0]) / S
        y = (R[1, 2] + R[2, 1]) / S
        z = 0.25 * S

    return np.array([w, x, y, z])

#繞z軸用
import numpy as np

# 定義旋轉角度（弧度）
theta = np.pi / 2

# 計算旋轉矩陣
R_x = np.array([
    [1, 0, 0],
    [0, np.cos(theta), -np.sin(theta)],
    [0, np.sin(theta), np.cos(theta)]
])

print("Rotation matrix about z-axis (counter-clockwise 90 degrees):")
print(R_x)

# 旋轉矩陣
rotation_matrix = np.array([
[ 0.6949719   ,0.7165791  ,-0.05940002],
 [ 0.7186626  ,-0.69490093  ,0.02523281],
 [-0.02319583, -0.06022467 ,-0.99791527]])

# 轉換為四元數
#rotation_matrix=R_x@rotation_matrix
    # 轉換為四元數
quaternion = rotation_matrix_to_quaternion(rotation_matrix)
print("四元數：scipy")
print(quaternion)


Rotation matrix about z-axis (counter-clockwise 90 degrees):
[[ 1.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  6.123234e-17 -1.000000e+00]
 [ 0.000000e+00  1.000000e+00  6.123234e-17]]
四元數：scipy
[-0.02321464  0.92029725  0.38988536 -0.02243728]


In [32]:
import numpy as np

def normalize_quaternion(q):
    # 計算四元數的長度（模）
    tmp=math.sqrt(q[0]*q[0]+q[1]*q[1]+q[2]*q[2]+q[3]*q[3])
    print("原始平方和開根號")
    print(tmp)
    quat_norm=[q[0]/tmp,q[1]/tmp,q[2]/tmp,q[3]/tmp]
    return quat_norm
import math

# 範例
q = np.array([-0.01138644 , 0.01041642, -0.02108575  ,0.99965856])  # 示例四元数
normalized_q = normalize_quaternion(q)
print("Normalized quaternion:", normalized_q)

print("歸一化平方和開根號")
print(math.sqrt(normalized_q[0]*normalized_q[0]+normalized_q[1]*normalized_q[1]+normalized_q[2]*normalized_q[2]+normalized_q[3]*normalized_q[3]))

# from pyquaternion import Quaternion
# rot_4 = Quaternion(q[3],q[0],q[1],q[2])
# rot_4 = rot_4.normalised
# print(rot_4)

IndexError: index 3 is out of bounds for axis 0 with size 3

In [2]:
import numpy as np
from scipy.spatial.transform import Rotation as R

def quaternion_to_rotation_matrix(q):
    a, b, c, d = q
    R = np.array([[1 - 2*(c**2 + d**2), 2*(b*c - a*d), 2*(a*c + b*d)],
                  [2*(b*c + a*d), 1 - 2*(b**2 + d**2), 2*(c*d - a*b)],
                  [2*(b*d - a*c), 2*(a*b + c*d), 1 - 2*(b**2 + c**2)]])
    return R

# 四元數
quaternion = np.array([-0.679, 0.726, -0.074, -0.081])

# 轉換為旋轉矩陣
rotation_matrix = quaternion_to_rotation_matrix(quaternion)

print("旋轉矩陣：")
print(rotation_matrix)


r = R.from_quat(quaternion)
r.as_matrix()
print("旋轉矩陣：scipy")
print(rotation_matrix)

旋轉矩陣：
[[ 0.975926 -0.217446 -0.01712 ]
 [ 0.00255  -0.067274  0.997896]
 [-0.218104 -0.97392  -0.065104]]
旋轉矩陣：scipy
[[ 0.975926 -0.217446 -0.01712 ]
 [ 0.00255  -0.067274  0.997896]
 [-0.218104 -0.97392  -0.065104]]


In [5]:
def convert_coordinates(window_width, window_height, image_width, image_height, click_x, click_y):
    # 計算寬度和高度的比例因子
    width_scale = image_width / window_width
    height_scale = image_height / window_height
    
    # 將視窗中的點擊位置轉換為原始大小影像中的位置
    original_x = int(click_x * width_scale)
    original_y = int(click_y * height_scale)
    
    return original_x, original_y

# 視窗大小
window_width = 889
window_height = 500

# 原始影像大小
image_width = 640
image_height = 480

# 在視窗中的點擊位置
click_x = 300
click_y = 200

# 轉換為原始影像中的位置
original_x, original_y = convert_coordinates(window_width, window_height, image_width, image_height, click_x, click_y)

print("在原始影像中的位置：({}, {})".format(original_x, original_y))

在原始影像中的位置：(215, 192)


In [146]:
import pyrealsense2 as rs
pipeline = rs.pipeline()
#self.colorizer = rs.colorizer()
config = rs.config()
#self.config.enable_device('f0265339') #只有一隻相機就不用指定
config.enable_stream(rs.stream.depth, 640, 480, rs.format.z16, 30)
config.enable_stream(rs.stream.color, 640, 480, rs.format.bgr8, 30)
align_to = rs.stream.color
align = rs.align(align_to)
profile = pipeline.start(config)
depth_sensor = profile.get_device().first_depth_sensor()
depth_scale = depth_sensor.get_depth_scale()  
frames = pipeline.wait_for_frames()
aligned_frames = align.process(frames)
depth_frame = aligned_frames.get_depth_frame()
color_frame = aligned_frames.get_color_frame()
_intrin = depth_frame.profile.as_video_stream_profile().intrinsics
print(_intrin)
pipeline.stop()

[ 640x480  p[319.108 241.311]  f[611.058 611.026]  Inverse Brown Conrady [0 0 0 0 0] ]


In [147]:
import cv2
rvec=np.matrix([[-0.67507828],
                [ 0.3170204 ],
                [ 0.2399557 ]])

rmatx = 0
rmatx = cv2.Rodrigues(rvec,rmatx)[0]
r_mat2,_ = cv2.Rodrigues(rvec)
print(rmatx)
print(r_mat2)


NameError: name 'np' is not defined

In [3]:
import cv2
import numpy as np
import time
# 生成aruco标记
# 加载预定义的字典
cap = cv2.VideoCapture(0)


dist=np.array([ 4.90913179e-02 , 5.22699002e-01, -2.65209452e-03  ,1.13033224e-03,-2.17133474e+00])

mtx=np.array([[606.77737126 ,  0.      ,   321.63287183],[  0.     ,    606.70030146 ,236.95293136],[  0.    ,       0.    ,       1.        ]])

mtx=np.array([[398.12724231  , 0.      ,   304.35638757],
 [  0.       ,  345.38259888, 282.49861858],
 [  0.,           0.,           1.        ]])
font = cv2.FONT_HERSHEY_SIMPLEX #font for displaying text (below)

while True:
    ret, frame = cap.read()
    h1, w1 = frame.shape[:2]
    # 读取摄像头画面
    # 纠正畸变
    newcameramtx, roi = cv2.getOptimalNewCameraMatrix(mtx, dist, (h1, w1), 0, (h1, w1))
    dst1 = cv2.undistort(frame, mtx, dist, None, newcameramtx)
    x, y, w1, h1 = roi
    dst1 = dst1[y:y + h1, x:x + w1]
    frame=dst1


    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    cv2.aruco_dict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_7X7_250)
    parameters =  cv2.aruco.DetectorParameters()
    dst1 = cv2.undistort(frame, mtx, dist, None, newcameramtx)
    '''
    detectMarkers(...)
        detectMarkers(image, dictionary[, corners[, ids[, parameters[, rejectedI
        mgPoints]]]]) -> corners, ids, rejectedImgPoints
    '''

    detector = cv2.aruco.ArucoDetector(cv2.aruco_dict , parameters)
    corners, ids, rejected_img_points = detector.detectMarkers(frame)
    #使用aruco.detectMarkers()函数可以检测到marker，返回ID和标志板的4个角点坐标
    #corners, ids, rejectedImgPoints = cv2.aruco.detectMarkers(gray,aruco_dict,parameters=parameters)

#    如果找不打id
    if ids is not None:

        rvec, tvec, _ = cv2.aruco.estimatePoseSingleMarkers(corners, 0.05, mtx, dist)
        # 估计每个标记的姿态并返回值rvet和tvec ---不同
        # from camera coeficcients
        (rvec-tvec).any() # get rid of that nasty numpy value array error

#        aruco.drawAxis(frame, mtx, dist, rvec, tvec, 0.1) #绘制轴
#        aruco.drawDetectedMarkers(frame, corners) #在标记周围画一个正方形

        for i in range(rvec.shape[0]):
            cv2.aruco.drawAxis(frame, mtx, dist, rvec[i, :, :], tvec[i, :, :], 0.03)
            cv2.aruco.drawDetectedMarkers(frame, corners)
        ###### DRAW ID #####
        cv2.putText(frame, "Id: " + str(ids), (0,64), font, 1, (0,255,0),2,cv2.LINE_AA)


    else:
        ##### DRAW "NO IDS" #####
        cv2.putText(frame, "No Ids", (0,64), font, 1, (0,255,0),2,cv2.LINE_AA)


    # 显示结果框架
    cv2.imshow("frame",frame)

    key = cv2.waitKey(1)

    if key == 27:         # 按esc键退出
        print('esc break...')
        cap.release()
        cv2.destroyAllWindows()
        break

    if key == ord(' '):   # 按空格键保存
#        num = num + 1
#        filename = "frames_%s.jpg" % num  # 保存一张图像
        filename = str(time.time())[:10] + ".jpg"
        cv2.imwrite(filename, frame)


[ WARN:0@836.248] global cap_v4l.cpp:997 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@836.249] global obsensor_uvc_stream_channel.cpp:159 getStreamChannelGroup Camera index out of range


AttributeError: 'NoneType' object has no attribute 'shape'